# Generated by Django 5.1.1 on 2024-11-19 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="chat_log",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="game",
            name="current_context",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="game",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="server.user"
            ),
        ),
    ]
