# Generated by Django 5.1.1 on 2024-11-21 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0002_alter_game_chat_log_alter_game_current_context_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="character_class",
            field=models.CharField(default="Human", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="game",
            name="character_name",
            field=models.CharField(default="John Doe", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="game",
            name="character_race",
            field=models.CharField(default="fighter", max_length=50),
            preserve_default=False,
        ),
    ]
